### ISSUE TITLE
Empty summary.tsv file

### ISSUE THREAD

**Issue by pneumowidow** [sanger-pathogens/seroba#33]
Hi,

I downloaded seroba via conda and ran it as recommended. However, although I get pred.tsv output for all genomes, I don't get a summary.tsv output. I used a for loop to run the commands for all my genome files since it was easier that way (see below):
```
#define serotype
for f in ./*_1P.fastq
do
 base=$(basename $f "_1P.fastq")
 basebam=$(basename $f "_L1_out_1P.fastq")
 seroba runSerotyping $out/Pneumocat-dir/ ${base}_1P.fastq ${base}_2P.fastq $out/summary_out/seroBA_${basebam} &&
 seroba summary $out/summary_out/seroBA_${basebam}
done
```
When I realized that I didn't get the summary output file, I decided to run the `seroba summary` command for just one output folder (instead of the for loop), but that still didn't work. As you can see in the snapshot below, the size of the file remains 0 KB.

![image](https://user-images.githubusercontent.com/43600124/49367198-a0c7db80-f6eb-11e8-95cb-98e4bd3ebe7e.png)

Is there something I did wrong? Thanks for your help in advance.

**Comment by eppinglen** [comment]
Hi @pneumowidow,

the  "summary" function can not directly be used on the output folder. Instead you can use:
'''
seroba summary $out/summary_out/  
''''
after your for loop is done.

**Comment by pneumowidow** [comment]
Ahh...ok. makes sense. Thank you!
