### ISSUE TITLE
nucmer dependency error

### ISSUE THREAD

**Issue by jacorvar** [sanger-pathogens/seroba#46]
Hi,

I have installed KMC and Mummer. They are in the path and work. However, when I try to run seroba, it complains:

`ERROR: I tried to get the version of nucmer with: "/apps/mummer/4.0.0.beta2/bin/nucmer --version" and the output didn't match this regular expression: "^NUCmer \(NUCleotide MUMmer\) version ([0-9\.]+)"`

When I run `/apps/mummer/4.0.0.beta2/bin/nucmer --version` I get `4.0.0beta2`, which indeed does not match what sroba expects.

**Comment by tseemann** [comment]
@jacorvar I think you need mummer 3.x not the much-newer 4.x you are using.
