### ISSUE TITLE
Make a git tag for 1.0.2 ?

### ISSUE THREAD

**Issue by tseemann** [sanger-pathogens/seroba#50]
A `git tag v1.0.2 && git push --tags` would be great so we can fix/update the conda package.

**Comment by tseemann** [comment]
I've just realised the changes from https://github.com/sanger-pathogens/seroba/pull/49 aren't in this master yet,

**Comment by eppinglen** [comment]
Hi Torsten,

the changes have been merged and I've made a new release tag. Thank you for the feedback.  

Best,
Lennard
