### ISSUE TITLE
There is not detailed_serogroup_info in the output folder

### ISSUE THREAD

**Issue by juanjo255** [sanger-pathogens/seroba#79]
Hello!

I am trying to use SeroBA for serotyping a paired-end sequencing of a cultivated pneumococcus which has high coverage. 

At the end, I only got a **pred.tsv** that explicitly said what was my serotype. However, I would like to get **more information**, for example, about the **percentage of identity**. In the documentation, it said that the program would also output a **detailed_serogroup_info**, nonetheless it is not there. What could be wrong?

I downloaded seroBA using conda. I had to downgrade KMC to 3.1.2 and apply this [patch](https://github.com/sanger-pathogens/ariba/issues/327) for pysam.

I hope you can help me,

Thank you, 

Juan

**Comment by Oliver-Lorenz-dev** [comment]
Hi Juan!

We are now maintaining a new version of SeroBA which has an updated database and output file structure: https://github.com/sanger-bentley-group/seroba

Could you try running this version of SeroBA?

SeroBA will only output a `detailed_serogroup_info` file if the serotype cannot be resolved by kmer identity alone. It may be the case that the serotype in question can be resolved just using kmer identity.

SeroBA will print out the kmer identities for each serotype in the reference database in the terminal - they should look something like this:
```
/seroba/build/bin/kmc -k71  -ci4  -m2 -t1 16453_2#11_1.fastq.gz /lustre/scratch127/pam/teams/team284/ol6/update_seroba_db/monocle_test/seroba_nextflow/work/00/28956b4bb142da8b823b47999b2895/temp.kmcox9kmae_/16453_2#11 /lustre/scratch127/pam/teams/team284/ol6/update_seroba_db/monocle_test/seroba_nextflow/work/00/28956b4bb142da8b823b47999b2895/temp.kmcox9kmae_
/seroba/build/bin/kmc_tools simple /lustre/scratch127/pam/teams/team284/ol6/update_seroba_db/monocle_test/seroba_nextflow/work/00/28956b4bb142da8b823b47999b2895/temp.kmcox9kmae_/16453_2#11 /seroba/database/kmer_db/01/01 intersect /lustre/scratch127/pam/teams/team284/ol6/update_seroba_db/monocle_test/seroba_nextflow/work/00/28956b4bb142da8b823b47999b2895/temp.kmcox9kmae_/inter
0.15774599146383667
/seroba/build/bin/kmc_tools simple /lustre/scratch127/pam/teams/team284/ol6/update_seroba_db/monocle_test/seroba_nextflow/work/00/28956b4bb142da8b823b47999b2895/temp.kmcox9kmae_/16453_2#11 /seroba/database/kmer_db/02/02 intersect /lustre/scratch127/pam/teams/team284/ol6/update_seroba_db/monocle_test/seroba_nextflow/work/00/28956b4bb142da8b823b47999b2895/temp.kmcox9kmae_/inter
0.11302211302211303
```

Hope this helps.

Oli

**Comment by juanjo255** [comment]
Awesome. I will try it!

I will re-open if anything comes up. 

Thank you very much Oliver.
